### PR TITLE
Add external SD support

### PR DESCRIPTION
**Pull request by mac12m99**

### CODE REVIEW

**Comment by bigbiff** [comment]
Please use gerrit.twrp.me for pushing to our repos.

**Comment by mac12m99** [comment]
This repository is not present in gerrit.twrp.me, am i wrong?

**Comment by bigbiff** [comment]
Hi, I created the repository. Sorry for the inconvenience.

**Comment by mac12m99** [comment]
Thanks :+1: , could you create also 'android-8.1' branch?
I think i don't have the permission (prohibited by Gerrit: create not permitted for refs/heads/android-8.1).

**Comment by bigbiff** [comment]
Sorry, the branch is now pushed.

**Comment by eremitein** [comment]
hello!

i have a more complete patch

[twrp-3.2.3-0-daisy_zero_190130.patch.txt](https://github.com/TeamWin/android_device_xiaomi_daisy/files/2824702/twrp-3.2.3-0-daisy_zero_190130.patch.txt)


changes:
- added Wipe and reFormat support for external USB-OTG and SD-card drives
- fixed turninig off screen in offline charge mode
- added support for external sd card
- corrected display of Cyrillic (and other non-ASCII characters) in file names on external drives (utf8)
- changed hard file system specification (vfat) to "auto" for external OTG / SD-card drives

**Comment by bigbiff** [comment]
Please push it to gerrit.twrp.me for consideration.

**Comment by eremitein** [comment]
ok, i did it.

one question - where is file /init.rc in repository?

need include one line for offline charger correctly working, because now daisy logo screen not shutoff while charging in offline mode

--- init.rc 1970-01-01 06:00:00.000000000 +0600
+++ /tmp/twrp-installer-daisy-3.2.3-0_zero_190130/initrd/init.rc  2019-01-30 02:19:34.000000000 +0500
@@ -3,6 +3,7 @@
 import /init.recovery.service.rc
 import /init.recovery.vold_decrypt.rc
 import /init.recovery.${ro.hardware}.rc
+import /init.recovery.hlthchrg.rc

**Pull request closed without merging**
